### ISSUE TITLE
Make a website

### ISSUE THREAD

**Issue by mscroggs** [mscroggs/AVE#15]
We should have a website for playing JS versions of games and submitting games.

avegame.co.uk is available. Any better ideas for domain name?

**Comment by Giannie** [comment]
I tried to look into some .io domains because they're all the rage, but they are very expensive. I think avegame.co.uk sounds good.

What are your plans for hosting?

**Comment by mscroggs** [comment]
I can host it on the same place I host mscroggs.co.uk and klbfax.co.uk

**Comment by Giannie** [comment]
Ok, what are our plans on translating to js then? Room creation will have to happen server side right?

**Comment by mscroggs** [comment]
I need to think about this... Might be we can compile the game beforehand then run it all client side

**Comment by Giannie** [comment]
I suppose it could be compiled into a bunch of js objects as straight replacements for the python objects

**Comment by mscroggs** [comment]
We have http://avegame.co.uk and https://github.com/mscroggs/AVE-website. We will need a Javascript version for the website

**Comment by mscroggs** [comment]
Website works. Still need to build somewhere for people to upload their own games
