### ISSUE TITLE
Item names that depend on other items not implemented

### ISSUE THREAD

**Issue by mscroggs** [mscroggs/AVE#45]
... yet. I'm adding this to remind me to do it.

**Comment by mscroggs** [comment]
fixed

**Comment by mscroggs** [comment]
No items appear on the list of items. Needs fixing

**Comment by mscroggs** [comment]
Error seems to be due to my computer using a cached version of some of the javascript files. Works fine now.

**Comment by Giannie** [comment]
Can we have a mechanism of  forcing the change to clear if we update things?

**Comment by Giannie** [comment]
Cache, not change

**Comment by mscroggs** [comment]
yes, using a timestamp.

Eg. ask for `/ave/game.js?time=1471252307` instead of `/ave/game.js`

I will implement this this evening

**Comment by mscroggs** [comment]
Caching is fixed in 82118561d63ca31a5511b6e8561914f4e0e9d86a
