### ISSUE TITLE
Items disappear

### ISSUE THREAD

**Issue by mscroggs** [mscroggs/AVE#46]
when you stand up in the living room, you lose all of your items

**Comment by Giannie** [comment]
Does this happen in any other version?

**Comment by mscroggs** [comment]
Pretty sure not. Probably a bug in my javascript

**Comment by mscroggs** [comment]
... But I will test

**Comment by mscroggs** [comment]
I think the error is in the javascript implementation of removing an item. Removing an items seems to clear the entire list.

**Comment by mscroggs** [comment]
Fixed in d1b97790ec8417e833c44492db38396e7682c8f6 and 877283eee14843f4d6c94be0ca7cecc081b39003

**Comment by mscroggs** [comment]
nope

**Comment by mscroggs** [comment]
Actually fixed in 5c30bbefdbf2736d80ecdda4c9d00bc8231a8ca9
