### ISSUE TITLE
Direction controls

### ISSUE THREAD

**Issue by Giannie** [mscroggs/AVE#6]
The direction controls are the wrong way around. I don't want to change screen.py since you are working on it, but JOY_UP and JOY_DOWN need to be swapped.

**Comment by mscroggs** [comment]
I'll make it work both ways up this afternoon

**Comment by Giannie** [comment]
I don't think there's any need for both ways up. It's actually just backwards.

**Comment by Giannie** [comment]
Fixed https://github.com/mscroggs/AVE/commit/11f2a28cae26376019871757d20b2f67cbe8dff0
